#define KEYWORD 1
#define NUMBER 2
#define IDENTIFIER 3
#define WHITESPACE 4
#define PUNCTUATION 5
#define PARANTHESIS 6
#define ASSIGNMENT 7
#define ARITHMETIC 8
#define COMPARISON 9
#define ERROR 10

#define TOKEN_ARR {"KEYWORD", "NUMBER", "IDENTIFIER", "WHITESPACE", "PUNCTUATION", "PARANTHESIS", "ASSIGNMENT", "ARITHMETIC", "COMPARISON", "ERROR"}